/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import javax.swing.JOptionPane;

/**
 *
 * @author Breno
 */
public class TicTacToeInterface extends javax.swing.JFrame {

    private String caractere = " O";
    private boolean flag1 = false;
    private boolean flag2 = false;
    private boolean flag3 = false;
    private boolean flag4 = false;
    private boolean flag5 = false;
    private boolean flag6 = false;
    private boolean flag7 = false;
    private boolean flag8 = false;
    private boolean flag9 = false;
    private int contadorVelha = 0;
    private boolean won = false;

    /**
     * Creates new form TicTacToeInterface
     */
    public TicTacToeInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        quadro = new javax.swing.JLabel();
        espaco1 = new javax.swing.JTextField();
        espaco2 = new javax.swing.JTextField();
        espaco3 = new javax.swing.JTextField();
        espaco4 = new javax.swing.JTextField();
        espaco5 = new javax.swing.JTextField();
        espaco6 = new javax.swing.JTextField();
        espaco7 = new javax.swing.JTextField();
        espaco8 = new javax.swing.JTextField();
        espaco9 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        retryButton = new javax.swing.JButton();

        jScrollPane2.setViewportView(jEditorPane1);

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe");

        jPanel1.setLayout(null);

        quadro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/game.png"))); // NOI18N
        jPanel1.add(quadro);
        quadro.setBounds(70, 80, 263, 218);

        espaco1.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        espaco1.setBorder(null);
        espaco1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                espaco1MouseClicked(evt);
            }
        });
        espaco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espaco1ActionPerformed(evt);
            }
        });
        jPanel1.add(espaco1);
        espaco1.setBounds(80, 90, 60, 50);

        espaco2.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        espaco2.setBorder(null);
        espaco2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                espaco2MouseClicked(evt);
            }
        });
        espaco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espaco2ActionPerformed(evt);
            }
        });
        jPanel1.add(espaco2);
        espaco2.setBounds(160, 90, 80, 50);

        espaco3.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        espaco3.setBorder(null);
        espaco3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                espaco3MouseClicked(evt);
            }
        });
        jPanel1.add(espaco3);
        espaco3.setBounds(259, 90, 70, 50);

        espaco4.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        espaco4.setBorder(null);
        espaco4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                espaco4MouseClicked(evt);
            }
        });
        jPanel1.add(espaco4);
        espaco4.setBounds(79, 160, 60, 60);

        espaco5.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        espaco5.setBorder(null);
        espaco5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                espaco5MouseClicked(evt);
            }
        });
        jPanel1.add(espaco5);
        espaco5.setBounds(159, 160, 80, 60);

        espaco6.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        espaco6.setBorder(null);
        espaco6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                espaco6MouseClicked(evt);
            }
        });
        jPanel1.add(espaco6);
        espaco6.setBounds(259, 160, 70, 60);

        espaco7.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        espaco7.setBorder(null);
        espaco7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                espaco7MouseClicked(evt);
            }
        });
        jPanel1.add(espaco7);
        espaco7.setBounds(80, 240, 60, 50);

        espaco8.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        espaco8.setBorder(null);
        espaco8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                espaco8MouseClicked(evt);
            }
        });
        jPanel1.add(espaco8);
        espaco8.setBounds(160, 240, 80, 50);

        espaco9.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        espaco9.setBorder(null);
        espaco9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                espaco9MouseClicked(evt);
            }
        });
        jPanel1.add(espaco9);
        espaco9.setBounds(259, 240, 70, 50);

        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Jogador X");

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Jogador O");

        retryButton.setText("Retry");
        retryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retryButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(retryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(retryButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void espaco1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espaco1MouseClicked
        // TODO add your handling code here:        
        if (flag1 == false) {
            espaco1.setText(this.caractere);
            this.contadorVelha++;
            if (espaco1.getText().equals(this.caractere)
                    && espaco2.getText().equals(this.caractere)
                    && espaco3.getText().equals(this.caractere)) {
                this.won = true;
                JOptionPane.showMessageDialog(null, "Jogador" + this.caractere + " ganhou");
            } else {
                if (espaco1.getText().equals(this.caractere)
                        && espaco4.getText().equals(this.caractere)
                        && espaco7.getText().equals(this.caractere)) {
                    this.won = true;
                    JOptionPane.showMessageDialog(null, "Jogador" + this.caractere + " ganhou");
                } else {
                    if (espaco1.getText().equals(this.caractere)
                            && espaco5.getText().equals(this.caractere)
                            && espaco9.getText().equals(this.caractere)) {
                        this.won = true;
                        JOptionPane.showMessageDialog(null, "Jogador" + this.caractere + " ganhou");
                    }
                }
            }                        
            if (" O".equals(this.caractere)) {
                this.caractere = " X";
            } else {
                this.caractere = " O";
            }
            this.flag1 = true;
            if(this.contadorVelha == 9 && this.won == false){
                JOptionPane.showMessageDialog(null, "DEU VELHA");
            }
        }
    }//GEN-LAST:event_espaco1MouseClicked

    private void espaco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espaco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_espaco1ActionPerformed

    private void espaco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espaco2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_espaco2ActionPerformed

    private void espaco2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espaco2MouseClicked
        // TODO add your handling code here:
        if (flag2 == false) {
            espaco2.setText(this.caractere);
            this.contadorVelha++;
            if (espaco1.getText().equals(this.caractere)
                    && espaco2.getText().equals(this.caractere)
                    && espaco3.getText().equals(this.caractere)) {
                this.won = true;
                JOptionPane.showMessageDialog(null, "Jogador" + this.caractere + " ganhou");
            } else {
                if (espaco2.getText().equals(this.caractere)
                        && espaco5.getText().equals(this.caractere)
                        && espaco8.getText().equals(this.caractere)) {
                    this.won = true;
                    JOptionPane.showMessageDialog(null, "Jogador" + this.caractere + " ganhou");
                }
            }
            if (" O".equals(this.caractere)) {
                this.caractere = " X";
            } else {
                this.caractere = " O";
            }
            this.flag2 = true;
            if(this.contadorVelha == 9 && this.won == false){
                JOptionPane.showMessageDialog(null, "DEU VELHA");
            }
        }
    }//GEN-LAST:event_espaco2MouseClicked

    private void espaco3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espaco3MouseClicked
        // TODO add your handling code here:
        if (flag3 == false) {
            espaco3.setText(this.caractere);
            this.contadorVelha++;
            if (espaco1.getText().equals(this.caractere)
                    && espaco2.getText().equals(this.caractere)
                    && espaco3.getText().equals(this.caractere)) {
                this.won = true;
                JOptionPane.showMessageDialog(null, "Jogador" + this.caractere + " ganhou");
            } else {
                if (espaco3.getText().equals(this.caractere)
                        && espaco5.getText().equals(this.caractere)
                        && espaco7.getText().equals(this.caractere)) {
                    this.won = true;
                    JOptionPane.showMessageDialog(null, "Jogador" + this.caractere + " ganhou");
                } else {
                    if (espaco3.getText().equals(this.caractere)
                            && espaco6.getText().equals(this.caractere)
                            && espaco9.getText().equals(this.caractere)) {
                        this.won = true;
                        JOptionPane.showMessageDialog(null, "Jogador" + this.caractere + " ganhou");
                    }
                }
            }
            if (" O".equals(this.caractere)) {
                this.caractere = " X";
            } else {
                this.caractere = " O";
            }
            this.flag3 = true;
            if(this.contadorVelha == 9 && this.won == false){
                JOptionPane.showMessageDialog(null, "DEU VELHA");
            }
        }

    }//GEN-LAST:event_espaco3MouseClicked

    private void espaco4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espaco4MouseClicked
        // TODO add your handling code here:
        if (flag4 == false) {
            espaco4.setText(this.caractere);
            this.contadorVelha++;
            if (espaco1.getText().equals(this.caractere)
                    && espaco4.getText().equals(this.caractere)
                    && espaco7.getText().equals(this.caractere)) {
                this.won = true;
                JOptionPane.showMessageDialog(null, "Jogador" + this.caractere + " ganhou");
            } else {
                if (espaco4.getText().equals(this.caractere)
                        && espaco5.getText().equals(this.caractere)
                        && espaco6.getText().equals(this.caractere)) {
                    this.won = true;
                    JOptionPane.showMessageDialog(null, "Jogador" + this.caractere + " ganhou");
                }
            }
            if (" O".equals(this.caractere)) {
                this.caractere = " X";
            } else {
                this.caractere = " O";
            }
            this.flag4 = true;
            if(this.contadorVelha == 9 && this.won == false){
                JOptionPane.showMessageDialog(null, "DEU VELHA");
            }
        }
    }//GEN-LAST:event_espaco4MouseClicked

    private void espaco5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espaco5MouseClicked
        // TODO add your handling code here:
        if (flag5 == false) {
            espaco5.setText(this.caractere);
            this.contadorVelha++;
            if (espaco1.getText().equals(this.caractere)
                    && espaco5.getText().equals(this.caractere)
                    && espaco9.getText().equals(this.caractere)) {
                this.won = true;
                JOptionPane.showMessageDialog(null, "Jogador" + this.caractere + " ganhou");
            } else {
                if (espaco3.getText().equals(this.caractere)
                        && espaco5.getText().equals(this.caractere)
                        && espaco7.getText().equals(this.caractere)) {
                    this.won = true;
                    JOptionPane.showMessageDialog(null, "Jogador" + this.caractere + " ganhou");
                } else {
                    if (espaco4.getText().equals(this.caractere)
                            && espaco5.getText().equals(this.caractere)
                            && espaco6.getText().equals(this.caractere)) {
                        this.won = true;
                        JOptionPane.showMessageDialog(null, "Jogador" + this.caractere + " ganhou");
                    } else {
                        if (espaco2.getText().equals(this.caractere)
                                && espaco5.getText().equals(this.caractere)
                                && espaco8.getText().equals(this.caractere)) {
                            this.won = true;
                            JOptionPane.showMessageDialog(null, "Jogador" + this.caractere + " ganhou");
                        }
                    }
                }
            }
            if (" O".equals(this.caractere)) {
                this.caractere = " X";
            } else {
                this.caractere = " O";
            }
            this.flag5 = true;
            if(this.contadorVelha == 9 && this.won == false){
                JOptionPane.showMessageDialog(null, "DEU VELHA");
            }
        }
    }//GEN-LAST:event_espaco5MouseClicked

    private void espaco6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espaco6MouseClicked
        // TODO add your handling code here:
        if (flag6 == false) {
            espaco6.setText(this.caractere);
            this.contadorVelha++;
            if (espaco3.getText().equals(this.caractere)
                    && espaco6.getText().equals(this.caractere)
                    && espaco9.getText().equals(this.caractere)) {
                this.won = true;
                JOptionPane.showMessageDialog(null, "Jogador" + this.caractere + " ganhou");
            } else {
                if (espaco4.getText().equals(this.caractere)
                        && espaco5.getText().equals(this.caractere)
                        && espaco6.getText().equals(this.caractere)) {
                    this.won = true;
                    JOptionPane.showMessageDialog(null, "Jogador" + this.caractere + " ganhou");
                }
            }
            if (" O".equals(this.caractere)) {
                this.caractere = " X";
            } else {
                this.caractere = " O";
            }
            this.flag6 = true;
            if(this.contadorVelha == 9 && this.won == false){
                JOptionPane.showMessageDialog(null, "DEU VELHA");
            }
        }
    }//GEN-LAST:event_espaco6MouseClicked

    private void espaco7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espaco7MouseClicked
        // TODO add your handling code here:
        if (flag7 == false) {
            espaco7.setText(this.caractere);
            this.contadorVelha++;
            if (espaco7.getText().equals(this.caractere)
                    && espaco5.getText().equals(this.caractere)
                    && espaco3.getText().equals(this.caractere)) {
                this.won = true;
                JOptionPane.showMessageDialog(null, "Jogador" + this.caractere + " ganhou");
            } else {
                if (espaco1.getText().equals(this.caractere)
                        && espaco4.getText().equals(this.caractere)
                        && espaco7.getText().equals(this.caractere)) {
                    this.won = true;
                    JOptionPane.showMessageDialog(null, "Jogador" + this.caractere + " ganhou");
                } else {
                    if (espaco7.getText().equals(this.caractere)
                            && espaco8.getText().equals(this.caractere)
                            && espaco9.getText().equals(this.caractere)) {
                        this.won = true;
                        JOptionPane.showMessageDialog(null, "Jogador" + this.caractere + " ganhou");
                    }
                }
            }
            if (" O".equals(this.caractere)) {
                this.caractere = " X";
            } else {
                this.caractere = " O";
            }
            this.flag7 = true;
            if(this.contadorVelha == 9 && this.won == false){
                JOptionPane.showMessageDialog(null, "DEU VELHA");
            }
        }
    }//GEN-LAST:event_espaco7MouseClicked

    private void espaco8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espaco8MouseClicked
        // TODO add your handling code here:
        if (flag8 == false) {
            espaco8.setText(this.caractere);
            this.contadorVelha++;
            if (espaco7.getText().equals(this.caractere)
                    && espaco8.getText().equals(this.caractere)
                    && espaco9.getText().equals(this.caractere)) {
                this.won = true;
                JOptionPane.showMessageDialog(null, "Jogador" + this.caractere + " ganhou");
            } else {
                if (espaco2.getText().equals(this.caractere)
                        && espaco5.getText().equals(this.caractere)
                        && espaco8.getText().equals(this.caractere)) {
                    this.won = true;
                    JOptionPane.showMessageDialog(null, "Jogador" + this.caractere + " ganhou");
                }
            }
            if (" O".equals(this.caractere)) {
                this.caractere = " X";
            } else {
                this.caractere = " O";
            }
            this.flag8 = true;
            if(this.contadorVelha == 9 && this.won == false){
                JOptionPane.showMessageDialog(null, "DEU VELHA");
            }
        }
    }//GEN-LAST:event_espaco8MouseClicked

    private void espaco9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espaco9MouseClicked
        // TODO add your handling code here:
        if (flag9 == false) {
            espaco9.setText(this.caractere);
            this.contadorVelha++;
            if (espaco3.getText().equals(this.caractere)
                    && espaco6.getText().equals(this.caractere)
                    && espaco9.getText().equals(this.caractere)) {
                this.won = true;
                JOptionPane.showMessageDialog(null, "Jogador" + this.caractere + " ganhou");
            } else {
                if (espaco1.getText().equals(this.caractere)
                        && espaco5.getText().equals(this.caractere)
                        && espaco9.getText().equals(this.caractere)) {
                    this.won = true;
                    JOptionPane.showMessageDialog(null, "Jogador" + this.caractere + " ganhou");
                } else {
                    if (espaco7.getText().equals(this.caractere)
                            && espaco8.getText().equals(this.caractere)
                            && espaco9.getText().equals(this.caractere)) {
                        this.won = true;
                        JOptionPane.showMessageDialog(null, "Jogador" + this.caractere + " ganhou");
                    }
                }
            }
            if (" O".equals(this.caractere)) {
                this.caractere = " X";
            } else {
                this.caractere = " O";
            }
            this.flag9 = true;
            if(this.contadorVelha == 9 && this.won == false){
                JOptionPane.showMessageDialog(null, "DEU VELHA");
            }
        }
    }//GEN-LAST:event_espaco9MouseClicked

    private void retryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retryButtonMouseClicked
    this.caractere = " O";
    this.flag1 = false;
    this.flag2 = false;
    this.flag3 = false;
    this.flag4 = false;
    this.flag5 = false;
    this.flag6 = false;
    this.flag7 = false;
    this.flag8 = false;
    this.flag9 = false;
    this.contadorVelha = 0;
    this.won = false;
    this.espaco1.setText("");
    this.espaco2.setText("");
    this.espaco3.setText("");
    this.espaco4.setText("");
    this.espaco5.setText("");
    this.espaco6.setText("");
    this.espaco7.setText("");
    this.espaco8.setText("");
    this.espaco9.setText("");
    }//GEN-LAST:event_retryButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToeInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField espaco1;
    private javax.swing.JTextField espaco2;
    private javax.swing.JTextField espaco3;
    private javax.swing.JTextField espaco4;
    private javax.swing.JTextField espaco5;
    private javax.swing.JTextField espaco6;
    private javax.swing.JTextField espaco7;
    private javax.swing.JTextField espaco8;
    private javax.swing.JTextField espaco9;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel quadro;
    private javax.swing.JButton retryButton;
    // End of variables declaration//GEN-END:variables
}
